/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.distribution.view;

import com.distribution.common.UserTrace;
import com.distribution.controller.DistributionController;
import com.distribution.controller.ProductController;
import com.distribution.model.Distribution;
import com.distribution.model.Product;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import java.awt.event.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Sanjaya Koju
 */
public class DistributionDetail extends javax.swing.JInternalFrame {
    //private Object place;
    private String place;

    
    private void printBill()
    {
        int count=jTable_distribution.getRowCount();
        String str="Nepal Oil Cooperation\n Sinamangal , Kathmandu\n";
        for(int i=0;i<count;i++)
        {
            str+=jTable_distribution.getValueAt(i,0).toString()+" ";
            str+=jTable_distribution.getValueAt(i,1).toString()+" ";
            str+=jTable_distribution.getValueAt(i,2).toString()+" ";
            str+=jTable_distribution.getValueAt(i,3).toString()+" ";
            str+=jTable_distribution.getValueAt(i,4).toString()+" ";
            str+=jTable_distribution.getValueAt(i,6).toString()+" ";
            str+=jTable_distribution.getValueAt(i,7).toString()+" ";
            str+=jTable_distribution.getValueAt(i,5).toString()+" "+"\n";
            
        }
        str+="Grand Total:"+jLabel_total.getText();
        str+="\nThank You For Visiting!!!";
        
        BillPrint ob=new BillPrint();
        ob.jTextArea_bill.setLineWrap(true);
        ob.jTextArea_bill.setText(str);
        try
        {
            ob.jTextArea_bill.print();
        }
        catch(Exception ex)
        {
            System.out.println(ex);
        }
    }
    /**
     * Creates new form Distribution
     */
    DefaultTableModel model;
    public DistributionDetail() {
        initComponents();
    
    
        
   
        initComponents();
        //jLabel_date.setText(new Date().toString());
        model=new DefaultTableModel(null,new String[]{"PId","Name","Qty","Price","Total","Date","CheckedBy","Place"});
        jTable_distribution.setModel(model);
        jLabel_distDate.setText(new Date().toString());
        jLabel_logged.setText("Logged In As "+UserTrace.username);
        
    }
    private void grandTotal()
    {
        int count = jTable_distribution.getRowCount();
            double total=0;
            for(int i=0;i<count;i++)
            {
                total+=Double.parseDouble(jTable_distribution.getValueAt(i,4).toString());     
            }
            jLabel_total.setText(total+"");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField_productId = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_distribution = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel_total = new javax.swing.JLabel();
        jButton_deleteDt = new javax.swing.JButton();
        jLabel_logged = new javax.swing.JLabel();
        jButton_saveAndPrint = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel_distDate = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField_place = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField_dqty = new javax.swing.JTextField();

        setClosable(true);
        setTitle("Distribution");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 153));
        jLabel1.setText("Product Id");

        jTextField_productId.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextField_productId.setForeground(new java.awt.Color(255, 0, 51));
        jTextField_productId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_productIdActionPerformed(evt);
            }
        });

        jTable_distribution.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable_distribution);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 51));
        jLabel2.setText("Grand Total");

        jLabel_total.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_total.setForeground(new java.awt.Color(255, 0, 51));

        jButton_deleteDt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_deleteDt.setForeground(new java.awt.Color(255, 0, 0));
        jButton_deleteDt.setIcon(new javax.swing.ImageIcon("D:\\Icons\\if_button_fewer_7697.png")); // NOI18N
        jButton_deleteDt.setText("Delete");
        jButton_deleteDt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_deleteDtActionPerformed(evt);
            }
        });

        jLabel_logged.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_logged.setForeground(new java.awt.Color(255, 0, 0));
        jLabel_logged.setText("jLabel3");

        jButton_saveAndPrint.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_saveAndPrint.setForeground(new java.awt.Color(255, 0, 0));
        jButton_saveAndPrint.setIcon(new javax.swing.ImageIcon("D:\\Icons\\if_Button White Load_58497.png")); // NOI18N
        jButton_saveAndPrint.setText("Save and Print");
        jButton_saveAndPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_saveAndPrintActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 0, 204));
        jLabel3.setText("Date");

        jLabel_distDate.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_distDate.setForeground(new java.awt.Color(255, 0, 204));
        jLabel_distDate.setText("jLabel4");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 204));
        jLabel4.setText("Place");

        jTextField_place.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextField_place.setForeground(new java.awt.Color(255, 0, 51));
        jTextField_place.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_placeActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 0, 204));
        jLabel5.setText("Qty");

        jTextField_dqty.setForeground(new java.awt.Color(255, 0, 0));
        jTextField_dqty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_dqtyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 698, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel_logged)
                                .addGap(192, 192, 192)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel_total, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(77, 77, 77))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel_distDate, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextField_productId, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton_deleteDt, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(165, 165, 165))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField_place, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField_dqty, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton_saveAndPrint)
                .addGap(145, 145, 145))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel_distDate))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField_place, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_dqty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton_deleteDt)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField_productId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1)))
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jLabel_logged))
                    .addComponent(jLabel_total, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(jButton_saveAndPrint)
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_productIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_productIdActionPerformed
        // TODO add your handling code here:
        UserTrace ut=new UserTrace();
        String str=jTextField_productId.getText();
        place = jTextField_place.getText();
        int qty =Integer.parseInt(jTextField_dqty.getText());
        qty=Math.abs(qty);
        double total;
        if(!str.equals(""))
        {
            int pid=Integer.parseInt(str);
            ProductController pdc=new ProductController();
            Product ob=pdc.fetchData(pid);
            if(!(pid >='0' && pid <='9'))
            {
                //evt.consume();
            }
            if(ob!=null)
            {
                total=qty*ob.getPrice();
                model.addRow(new Object[]{ob.getId(),ob.getNames(),qty,ob.getPrice(),total,new Date().toGMTString(),ut.getUsername(),place});
            }
            
            grandTotal();
        }
        jTextField_productId.setText("");
        jTextField_place.setText("");
        jTextField_dqty.setText("");
    }//GEN-LAST:event_jTextField_productIdActionPerformed

    private void jButton_deleteDtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_deleteDtActionPerformed
        // TODO add your handling code here:
        int rowIndex=jTable_distribution.getSelectedRow();
        if(rowIndex>=0)
        {
            model.removeRow(rowIndex);
            grandTotal();
        }
    }//GEN-LAST:event_jButton_deleteDtActionPerformed

    private void jButton_saveAndPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_saveAndPrintActionPerformed
        // TODO add your handling code here:
         ArrayList<Distribution> list=new ArrayList();
         int count=jTable_distribution.getRowCount();
         
         for(int i=0;i<count;i++)
        {
            Distribution ob=new Distribution();
            int did=UserTrace.id;
            int pid=Integer.parseInt(jTable_distribution.getValueAt(i,0).toString());
            String names=jTable_distribution.getValueAt(i,1).toString();
            
            int qty=Integer.parseInt(jTable_distribution.getValueAt(i,2).toString());
            int price=(int) Double.parseDouble(jTable_distribution.getValueAt(i,3).toString());
            double total=Double.parseDouble(jTable_distribution.getValueAt(i,4).toString());
            java.util.Date d=new java.util.Date();
            //String d=new java.util.Date().toString();
            String checkedBy=(jTable_distribution.getValueAt(i,6).toString());
            place=(jTable_distribution.getValueAt(i,7).toString());
            
            ob.setPid(pid);
            ob.setDid(did);
            ob.setNames(names);
            ob.setPrice(price);
            ob.setQty(qty);
            ob.setDate(d);
            ob.setCheckedBy(checkedBy);
            ob.setPlace(place);
            ob.setTotal(total);
            
            list.add(ob);
             
        }
        DistributionController sdc=new DistributionController();
        sdc.saveData(list);
        //JOptionPane.showMessageDialog(null,"Record Saved");
       printBill();

    
    }//GEN-LAST:event_jButton_saveAndPrintActionPerformed

    private void jTextField_placeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_placeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_placeActionPerformed

    private void jTextField_dqtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_dqtyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_dqtyActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_deleteDt;
    private javax.swing.JButton jButton_saveAndPrint;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel_distDate;
    private javax.swing.JLabel jLabel_logged;
    private javax.swing.JLabel jLabel_total;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_distribution;
    private javax.swing.JTextField jTextField_dqty;
    private javax.swing.JTextField jTextField_place;
    private javax.swing.JTextField jTextField_productId;
    // End of variables declaration//GEN-END:variables

   
}
